### ISSUE TITLE
Tracking issue for switching to `assert_lint_err!` macro

### ISSUE THREAD

**Issue by magurotuna** [denoland/deno_lint#431]
This is a tracking issue for switching from `assert_lint_err` functions to `assert_lint_err!` macro.

I introduced the new test utility macro `assert_lint_err!` which allows us to make sure lint error messages and hints are equal to what we expect.
Now we would like to replace the functions with the macro.

The current statuses of the rules:
(✅ means it is included in the recommended rules)

- [x] adjacent-overload-signatures ✅ (#410)
- [x] ban-ts-comment ✅ (#410)
- [x] ban-types ✅ (#435)
- [x] ban-untagged-ignore ✅ (#436)
- [x] ban-untagged-todo (#537)
- [x] camelcase ✅ (#410)
- [x] constructor-super ✅ (#434)
- [x] default-param-last (#684)
- [x] eqeqeq (#684)
- [x] explicit-function-return-type (#684)
- [x] explicit-module-boundary-types (#684)
- [x] for-direction ✅ (#437)
- [x] getter-return ✅ (#446)
- [x] no-array-constructor ✅ (#442)
- [x] no-async-promise-executor ✅ (#442)
- [x] no-await-in-loop (#442)
- [x] no-case-declarations ✅ (#447)
- [x] no-class-assign ✅ (#448)
- [x] no-compare-neg-zero ✅ (#507)
- [x] no-cond-assign ✅ (#508)
- [x] no-const-assign (#684)
- [x] no-constant-condition ✅ (#511)
- [x] no-control-regex ✅ (#512)
- [x] no-debugger ✅ (#515)
- [x] no-delete-var ✅ (#455)
- [x] no-dupe-args ✅ (#516)
- [x] no-dupe-class-members ✅ (#517)
- [x] no-dupe-else-if ✅ (#518)
- [x] no-dupe-keys ✅ (#519)
- [x] no-duplicate-case ✅ (#520)
- [x] no-empty ✅ (#474)
- [x] no-empty-character-class ✅ (#442)
- [x] no-empty-interface ✅ (#526)
- [x] no-empty-pattern ✅ (#442)
- [x] no-eval (#490)
- [x] no-ex-assign ✅ (#442)
- [x] no-explicit-any ✅ (#442)
- [x] no-extra-boolean-cast ✅ (#530)
- [x] no-extra-non-null-assertion ✅ (#531)
- [x] no-extra-semi ✅ (#535)
- [x] no-fallthrough ✅ (#539)
- [x] no-func-assign ✅ (#540)
- [x] no-global-assign ✅ (#542)
- [x] no-import-assign ✅
- [x] no-inferrable-types ✅ (#543)
- [x] no-inner-declarations ✅ (#544)
- [x] no-invalid-regexp ✅ (#455)
- [x] no-irregular-whitespace ✅ (#551)
- [x] no-misused-new ✅ (#565)
- [x] no-mixed-spaces-and-tabs ✅ (#573)
- [x] no-namespace ✅ (#575)
- [x] no-new-symbol ✅ (#578)
- [x] no-non-null-asserted-optional-chain (#684)
- [x] no-non-null-assertion (#684)
- [x] no-obj-calls ✅ (#456)
- [x] no-octal ✅ (#456)
- [x] no-prototype-builtins ✅ (#456)
- [x] no-redeclare ✅ (#456)
- [x] no-regex-spaces ✅ (#579)
- [x] no-self-assign ✅ (#605)
- [x] no-setter-return ✅ (#632)
- [x] no-shadow-restricted-names ✅ (#606)
- [x] no-sparse-arrays (#684)
- [x] no-this-alias ✅ (#624)
- [x] no-this-before-super ✅ (#634)
- [x] no-throw-literal (#684)
- [x] no-undef ✅ (#410)
- [x] no-unreachable ✅ (#455)
- [x] no-unsafe-finally ✅ (#641)
- [x] no-unsafe-negation ✅ (#654)
- [x] no-unused-labels ✅ (#655)
- [x] no-unused-vars (#625)
- [x] no-var (#595)
- [x] no-with ✅ (#442)
- [x] prefer-as-const ✅ (#568)
- [x] prefer-const ✅ (#527)
- [x] prefer-namespace-keyword ✅ (#442)
- [x] require-await ✅ (#514)
- [x] require-yield ✅ (#442)
- [x] single-var-declarator (#684)
- [x] triple-slash-reference ✅ (#684)
- [x] use-isnan ✅ (#684)
- [x] valid-typeof ✅ (#438)

**Comment by magurotuna** [comment]
I'd appreciate it if anyone helped us to migrate to `assert_lint_err!` macro.
If you are interested in it, consider using [magurotuna/switch2macro-dlint](https://github.com/magurotuna/switch2macro-dlint). I think it will save your time, although it is a very ad-hoc tool.

**Comment by kamchy** [comment]
There are not many rules to refactor left, perhaps I could help here?

**Comment by ry** [comment]
@kamchy Help is always appreciated!

I'm not sure what the best rule to get started on is tho... Maybe @bartlomieju can recommend one?

**Comment by bartlomieju** [comment]
@kamchy thanks! There's not much difference between the rules left - this task is mostly about switching rules from using `assert_lint_err::<>` and `assert_lint_err_n::<>` to using `assert_lint_err!` macro. I think starting with [`eqeqeq`](https://github.com/denoland/deno_lint/blob/main/src/rules/eqeqeq.rs) might be good first try. As an example here's how to use `assert_lint_err!` macro [in `for_direction` rule](https://github.com/denoland/deno_lint/blob/dcf5c878aaf985f39a05a8aca9f5c6e2bb57ee63/src/rules/for_direction.rs#L242)

**Comment by kamchy** [comment]
Thanks for the example. Should I issue separate PRs for each rule I've refactored or just single PR?

**Comment by magurotuna** [comment]
> Should I issue separate PRs for each rule I've refactored or just single PR?

I think either way is fine!

**Comment by magurotuna** [comment]
@bartlomieju we've completed all replacement, this issue can be closed now😉
