### ISSUE TITLE
ESLint recommended rules

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_lint#48]
Tracking issue for rules from `eslint:recommended` set.

- [x] constructor-super
- [x] for-direction
- [x] getter-return
- [x] no-async-promise-executor
- [x] no-case-declarations
- [x] no-class-assign (<i>broken, needs scope analysis</i>)
- [x] no-compare-neg-zero
- [x] no-cond-assign
- [x] no-const-assign (<i>broken, needs scope analysis</i>)
- [x] no-constant-condition
- [x] no-control-regex <i>(easy)</i>
- [x] no-debugger
- [x] no-delete-var
- [x] no-dupe-args
- [x] no-dupe-class-members
- [x] no-dupe-else-if
- [x] no-dupe-keys
- [x] no-duplicate-case
- [x] no-empty
- [x] no-empty-character-class
- [x] no-empty-pattern
- [x] no-ex-assign (<i>broken, needs scope analysis</i>)
- [x] no-extra-boolean-cast
- [x] no-extra-semi
- [x] no-fallthrough <i>(hard, needs code path analysis)</i>
- [x] no-func-assign (<i>broken, needs scope analysis</i>)
- [x] no-global-assign <i>(hard, needs scope analysis)</i>
- [x] no-import-assign <i>(hard, needs scope analysis)</i>
- [x] no-inner-declarations 
- [x] no-invalid-regexp<i>(<s>easy</s> hard, need to port additional lib)</i>
- [x] no-irregular-whitespace <i>(easy)</i>
- [ ] no-misleading-character-class <i>(easy)</i>
- [x] no-mixed-spaces-and-tabs
- [x] no-new-symbol
- [x] no-obj-calls
- [x] no-octal
- [x] no-prototype-builtins
- [x] no-redeclare <i>(hard, needs scope analysis)</i>
- [x] no-regex-spaces
- [x] no-self-assign 
- [x] no-setter-return
- [x] no-shadow-restriced-names
- [x] no-sparse-arrays
- [x] no-this-before-super
- [x] no-undef <i>(hard, needs scope analysis)</i>
- [x] no-unexpected-multiline <i>(easy)</i>
- [x] no-unreachable <i>(hard, needs code path analysis)</i>
- [x] no-unsafe-finally
- [x] no-unsafe-negation
- [x] no-unused-labels
- [x] no-unused-vars <i>(hard, needs scope analysis)</i>
- [x] <s>no-useless-escape <i>(easy)</i></s> (https://github.com/denoland/deno_lint/issues/48#issuecomment-666285937)
- [x] no-with
- [x] require-yield
- [x] use-isnan
- [x] valid-typeof

**Comment by bartlomieju** [comment]
Update: there are still some rules that can be implemented right now (eg. `no-extra-boolean-cast`, `no-dupe-class-members`), but a lot others are blocked by scope analysis (#160)

**Comment by magurotuna** [comment]
Is there anyone working on `no-extra-boolean-cast`? If none, I'd like to take it.

**Comment by bartlomieju** [comment]
@magurotuna go ahead!

**Comment by magurotuna** [comment]
`no-dupe-else-if` rule seems able to be implemented without scope analysis. I will work on this rule next.

**Comment by humancalico** [comment]
I am working on `no-constant-condition`

**Comment by magurotuna** [comment]
I'm working on `no-extra-semi`. Some fix to `swc` is needed to implement this rule, so I asked at https://github.com/swc-project/swc/issues/874

**Comment by magurotuna** [comment]
As `no-extra-semi` is pended, I am working on `no-control-regex` instead.

**Comment by AkinAguda** [comment]
I am working on `no-irregular-whitespace`

**Comment by qkniep** [comment]
I am working on `no-invalid-regexp`.

**Comment by qkniep** [comment]
Is `no-invalid-regexp` really that easy to implement? I can't simply check via Rust's regex crate as the feature set is different from ECMAScript's (e.g. Rust's regex has no lookahead/-behind), right? And as far as I have seen, there is no crate which implements ECMAScript's regex syntax. In ESLint they use regexpp's validator: https://github.com/mysticatea/regexpp/blob/master/src/validator.ts

Thus, now I think I would have to implement something like that in Rust. I would be interested in doing this, but before starting I would like to know if I am right in the assumption or if I am being oblivious to something.

**Comment by bartlomieju** [comment]
> Is `no-invalid-regexp` really that easy to implement? I can't simply check via Rust's regex crate as the feature set is different from ECMAScript's (e.g. Rust's regex has no lookahead/-behind), right? And as far as I have seen, there is no crate which implements ECMAScript's regex syntax. In ESLint they use regexpp's validator: https://github.com/mysticatea/regexpp/blob/master/src/validator.ts
> 
> Thus, now I think I would have to implement something like that in Rust. I would be interested in doing this, but before starting I would like to know if I am right in the assumption or if I am being oblivious to something.

@qkniep it seems that this rule is not easy after all, I'll change the description. You're correct that you can't use Rust's regex crate - you don't want to parse using Rust rules, but perform JS regex analysis, so I guess porting `regexpp` is the way to solve it. Feel free to skip this one if that's too much work.

**Comment by qkniep** [comment]
Ok, I will start with `no-unexpected-multiline` then. And come back to the regex one later.

**Comment by qkniep** [comment]
I created a PR (#243) for `no-unexpected-multiline`.
Also I started work on porting regexpp to Rust over here: [https://github.com/qkniep/regexpp-rs](https://github.com/qkniep/regexpp-rs).

**Comment by qu4k** [comment]
Taking a closer look on `no-useless-escape` I found out that [`swc_ecma_ast::Str`](https://swc-project.github.io/rustdoc/swc_ecma_ast/struct.Str.html) (StringLiteral) value is already escaped (there is a `has_escape` flag in the struct, but it's intrinsic to the string and not the single characters). 
The rule cannot be implemented fully if this information is not available in the visitor.

**Comment by humancalico** [comment]
working on `no-misleading-character-class`

**Comment by kdy1** [comment]
I'm working on `no-global-assign` and `no-import-assign`.
`no-global-assign` is blocked by https://github.com/denoland/deno_lint/pull/304/files

**Comment by bartlomieju** [comment]
We're left with `no-misleading-character-class` that is a single not implemented rule. There is PR going (#278) which requires to port some additional code. This rule is not critical, so I'm gonna close this issue as resolved.
