### ISSUE TITLE
Integration with Deno CLI

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_lint#78]
Tracking issue for all things that need to be worked out before linter can be integrated with Deno CLI

- [x] CLI integration (clap)
- [x] source file loading
- [x] error handling
- [x] dependency duplication (`termcolor`)
- [x] publish crate with `lib.rs` to crates.io (#83)

**Comment by bartlomieju** [comment]
Closing as resolved, because integration with Deno CLI is going smoothly.
