### ISSUE TITLE
typescript-eslint recommended rules

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno_lint#86]
Tracking issues for recommended rules of typescript-eslint

https://github.com/typescript-eslint/typescript-eslint/blob/v3.1.0/packages/eslint-plugin/src/configs/recommended.ts

- [x] adjacent-overload-signatures <i>(easy)</i>
- [x] ban-ts-comment
- [x] ban-types
- [x] explicit-module-boundary-types <i>(easy)</i>
- [x] no-array-constructor
- [x] no-empty-function (needs to be fixed, false positives for constructors)
- [x] no-empty-interface
- [x] no-explicit-any
- [x] no-extra-non-null-assertion
- [x] no-extra-semi <i>(easy)</i>
- [x] no-inferrable-types <i>(easy)</i>
- [x] no-misused-new
- [x] no-namespace
- [x] no-non-null-asserted-optional-chain
- [x] no-non-null-assertion
- [x] no-this-alias
- [x] no-unused-vars <i>(hard, needs scope analysis)</i>
- [x] <s>no-var-requires</s>
- [x] prefer-as-const
- [x] prefer-namespace-keyword
- [x] triple-slash-reference

**Comment by lucacasonato** [comment]
I don't think `no-var-requires` makes sense for us: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-var-requires.md

**Comment by bartlomieju** [comment]
I've marked this issue with `0.2.0` milestone. I want to implement remaining rules this week so they will be included in `deno v1.1`

**Comment by disizali** [comment]
@bartlomieju
i'm almost done with `no-this-alias` and `ban-ts-comment`,
Also `no-inferrable-types` is my next goal.
you can start the rest first.

**Comment by iykekings** [comment]
I'm working on `no-non-null-asserted-optional-chain` and `no-non-null-assertion`.

**Comment by bartlomieju** [comment]
@iykekings are you still working on `no-non-null-asserted-optional-chain`?

**Comment by iykekings** [comment]
Yes, had plenty on my plate at work. I will try to finish it ASAP

**Comment by magurotuna** [comment]
I'm working on `adjacent-overload-signatures`.

**Comment by humancalico** [comment]
@bartlomieju It seems `no-inferrable-types` is done. It's not updated in your comment

**Comment by qu4k** [comment]
Taking `explicit-module-boundary-types`

**Comment by bartlomieju** [comment]
Done with #267
